### PR TITLE
Seek and report unused translations

### PR DESCRIPTION
**Pull request by bkuri**
The PR aims to introduce a new method, `seekUnusedTranslations`, to assist with translation management, along with a new option called `lintGlobs` that allows for an array of relative paths like so:

```js
{
  'translation-manager': {
    lintGlobs: ['*', 'components/**/*', 'composables/*', 'content/**/*', 'layouts/*', 'pages/**/*', 'plugins/*', 'store/*'],
  }
}
```

It was built to recursively seek for translation keys that are theoretically unused or partially matched in specific file types of the codebase (`.json`, `.md`, `.ts`, `.vue`, `.yml` for the time being).

The primary features include scanning directories for the mentioned file types, a flexible matching algorithm to account for direct or partial matches of translation keys within files, fast line-by-line reading that consumes minimal memory, and concise reporting of all detected unused translation keys every time translations are generated.

This should help reduce the project’s overall clutter, contributing to improving maintainability and performance.

There's a few hardcoded settings. which may or may not need to be adjusted (or turned into proper module options):

`REGEX_FILE_EXTENSIONS`: (default: `/\.(json|md|ts|vue|yml)$/i`) which file types to load
`SEGMENT_MIN_LENGTH`: (default: `2`) keys with less number of segments are ignored
`SEGMENT_PASS_THRESHOLD`: (default 0.5) If this majority of segments match then mark as "found"

The first setting is self-explanatory, but the other two might need a bit more help.

A translation key typically looks like this: `APP_LANDING_TITLE`. In this example, this key is made up of 3 segments, separated by `_`.

The `seekUnusedTranslations` method will look for complete keys like the above, but will also attempt to look for partial keys (ie `APP LANDING`, `LANDING TITLE`, `APP TITLE`, etc). If enough segments are found in a line then the key is added to the "maybe" list.

Once all keys have been processed a small report should appear in the console with the results.

Of course, this is a bit opinionated and it assumes a few things about how keys are specified, such as the key separator (`_` in this case) and the minimum number of segments that would be evaluated. Also searches are case-sensitive for both precision and performance reasons, so these may be some factors that may need further tweaking before this is considered for release.

At any rate, I've been using it for a few days and it's been running very well, with very little overhead that I can tell.

Hope it's helpful to the project!

### CODE REVIEW

**Comment by samk-dev** [comment]
@bkuri thank you so much for the contribution I like the idea so much as it will reduce the size of the final translation string.

I will take at a look at tonight and let you know :) sorry for the late reply it's been crazy weeks at work

regards

**Comment by bkuri** [comment]
@samk-dev no worries! :smile: 

I've been using it non-stop for about a month or so for a medium-sized project that I'm working on and it's super fast, although I'm using a higher-end PC with an SSD. It might be worth testing it on bigger projects with lots of keys under an HDD, for example, but I'm pretty confident that performance should be quite good in those cases as well.

Looking forward to your feedback when you have some time!

**Comment by bkuri** [comment]
@samk-dev just wanted to let you know that I've been using both this PR and #15 and they both work well.

Have you perhaps had a chance to review them yet? If so it would be cool to get them merged so that I can point to the official package inside my `package.json` once again.

Otherwise please let me know if there's something that you would like to see changed and I'll see what I can do.

Muchas gracias de antemano! :smile:

**Comment by samk-dev** [comment]
Hey @bkuri, I have tested the feature on

- fresh projects and works good
- recently upgraded projects from Nuxt 2 to 3 and it did not work
- existing Nuxt 3 projects which on the majority didn't work

The reason why it did not work, is because of this: `A translation key typically looks like this: APP_LANDING_TITLE. In this example, this key is made up of 3 segments, separated by _.`

Assuming that everyone is maintaining the translations of an App or Website are all developers is a bit risky. Most of websites has a marketing team which are non technical people which they use Pages, Excel, Sheets and most established projects has no naming conventions, example translation key patterns that I found is `translation-string` from static content and for some that comes from a CMS or API for some short descriptions they're wrapped inside a quotes and there's no separator of any kind 😂 something like this `"when an unknown printer took a galley of type and scrambled it to make a type specimen book"`  this scenarios are mostly common in ecommerce sites where a lot of stuff happens dynamically.

For a fresh project we can enforce some conventions on naming but on existing projects it's a lot of work for most people I know using the module which involves a lot of refactor and people are lazier than you think.


We can see at some point on how to make it flexible, and maybe opt-in so it loads the code only for those who opt-in.

Later I will open issues for new features that has been requested and that are also useful if you wanna take a lot an contribute to the project :)

Thank you

**Review by samk-dev — COMMENTED** [review]
Hey @bkuri, I have tested the feature on

- fresh projects and works good
- recently upgraded projects from Nuxt 2 to 3 and it did not work
- existing Nuxt 3 projects which on the majority didn't work

The reason why it did not work, is because of this: `A translation key typically looks like this: APP_LANDING_TITLE. In this example, this key is made up of 3 segments, separated by _.`

Assuming that everyone is maintaining the translations of an App or Website are all developers is a bit risky. Most of websites has a marketing team which are non technical people which they use Pages, Excel, Sheets and most established projects has no naming conventions, example translation key patterns that I found is `translation-string` from static content and for some that comes from a CMS or API for some short descriptions they're wrapped inside a quotes and there's no separator of any kind 😂 something like this `"when an unknown printer took a galley of type and scrambled it to make a type specimen book"`  this scenarios are mostly common in ecommerce sites where a lot of stuff happens dynamically.

For a fresh project we can enforce some conventions on naming but on existing projects it's a lot of work for most people I know using the module which involves a lot of refactor and people are lazier than you think.


We can see at some point on how to make it flexible, and maybe opt-in so it loads the code only for those who opt-in.

Later I will open issues for new features that has been requested and that are also useful if you wanna take a lot an contribute to the project :)

Mil gracias :) dispuesto a sugerencias

**Comment by samk-dev** [comment]
hey @bkuri I think I found a simple solution that might work.

step 1: this module could add `hooks` like `nuxt-i18n` does, example `onBeforeGeneratingTranslations`
step 2: anyone who wants/needs to do stuff before or after the build would be easy by creating a small complementary module to this

que te parece?

**Comment by bkuri** [comment]
@samk-dev you raise some good points regarding the key conventions (or lack thereof). Still, I do think that it's worth using in new projects, based on how it has already helped me in a couple of cases.

I like the hooks idea a lot, since that would allow users to add/remove modules such as this (and #15) on an opt-in basis.

I'm in the middle of a project at the moment, but I could work on a proposal in the coming days that would take a whack at implementing this, unless you already have a specific pattern in mind?

Saludos! :grin:

**Comment by samk-dev** [comment]
will implement hooks in upcoming release using [unjs hookable](https://github.com/unjs/hookable)

**Pull request closed without merging**
